---
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: 'module',
  ecmaFeatures: 
    jsx: true
rules:
  eqeqeq: 0
  indent: ["error", 4]
extends: 'standard'

    